# Generated by Django 5.0.4 on 2024-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(
                    choices=[('Employees', 'Employees'), ('Manager', 'Manager'), ('Director', 'Director'),
                             ('Vice President', 'Vice President'), ('CEO', 'CEO')], max_length=50)),
                ('department_name', models.CharField(
                    choices=[('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources'),
                             ('Sales', 'Sales'), ('IT', 'IT')], max_length=50)),
            ],
        ),
    ]
